### ISSUE TITLE
Troubleshoot, why Action is not running

### ISSUE THREAD

**Issue by robinmanuelthiel** [wemogy/get-release-version-action#1]
- See https://github.com/wemogy/project-management-demo/actions/runs/8011221431/job/21883959309
- Maybe a GitHub Action as Docker is the better idea, because then we have everything we need in one place. We already do this [here](https://github.com/wemogy/next-version-action/blob/main/action.yaml).

**Comment by SebastianKuesters** [comment]
@bennetrr for python argparse issue:

>The issue lies in how the --only-increase-suffix and --create-tag arguments are parsed in the script. In Python's argparse module, the type=bool conversion does not handle boolean values directly from the command line arguments. Instead, it interprets any non-empty string as True when using type=bool. So, even if you provide --only-increase-suffix false or --create-tag false, they will be interpreted as True.
