### ISSUE TITLE
Create Test Cases for all our Sceanrios

### ISSUE THREAD

**Issue by robinmanuelthiel** [wemogy/get-release-version-action#36]
We want one test case per Scenario (Release, Merge, Cherrypick, etc....) with branches.
Currently, all Tests happen on the default branch

### Test setup

1. Create a repository with main branch and 
2. Make initial commit (README.md) called `Initial commit`
3. Create branch `release` based on `main`
4. Create branch `release-beta` based on `release`
5. Create branch `release-prod` based on `release-beta`

### Scenarios

- [x] Call after initial commit
- [x] Call after one `chore` commit
- [x] Call after one commit of type `fix`, `feat` or `feat!`
- [x] Call after combinations of `chore`, `fix`, `feat` and `feat!` (`fix` + `fix` + `call`, `fix` + `feat` + `call`, ..., `feat!` + `feat!` + `call`)
- [x] Call after each commit, with combinations of `chore`, `fix`, `feat` or `feat!` (`fix` + `call` + `fix` + `call`, ...)
- [x] Call after one commit of type `fix`, `feat` or `feat!` and then a hotfix
- [x] Call after one commit of type `fix`, `feat` or `feat!` and then two hotfixes
- [x] Call after one commit of type `fix`, then a hotfix and then a commit of type `fix`, `feat` or `feat!`

**Comment by SebastianKuesters** [comment]
## How to do a Cherry-pick

Cherry-picking in Git involves applying a specific commit from one branch onto another branch. Here's how you can do it using the Git command line:

1. **Identify the Commit**: First, you need to identify the commit you want to cherry-pick. You can do this by checking the commit history using `git log` command.

   ```bash
   git log
   ```

   This will display a list of commits along with their commit IDs (hashes), commit messages, and other details.

2. **Switch Branch**: Switch to the branch where you want to apply the cherry-picked commit.

   ```bash
   git checkout <branch-name>
   ```

3. **Cherry-Pick**: Use the `git cherry-pick` command followed by the commit ID of the commit you want to apply.

   ```bash
   git cherry-pick <commit-id>
   ```

   Replace `<commit-id>` with the actual commit ID of the commit you want to cherry-pick.

4. **Resolve Conflicts (if any)**: If there are any conflicts during the cherry-pick process, Git will pause and ask you to resolve them manually. You can use `git status` to see which files have conflicts and then edit them to resolve conflicts. After resolving conflicts, use `git add` to mark the conflicts as resolved and continue the cherry-pick process by using:

   ```bash
   git cherry-pick --continue
   ```

5. **Finish**: Once you've resolved any conflicts and completed the cherry-pick, you can continue working on your branch or merge it with another branch as needed.

Remember that cherry-picking can lead to duplicated commits or conflicts, especially if you're cherry-picking changes from a branch with a different history. It's important to understand the implications of cherry-picking and ensure that it fits your workflow and project structure.

**Comment by SebastianKuesters** [comment]
## Expected Inputs & Outputs

### Merge from `release` to `release-beta` (First fix version)

Latest tag on `release`: `0.0.1-pre`

```python
ActionArguments(
    prefix='v',
    suffix='beta',
    previous_version_suffix='pre',
    bumping_suffix='hotfix',
    only_bump_suffix=True,
    create_tag=True
)

ActionOutputs(
    version='0.0.1-beta',
    version_name='v0.0.1-beta',
    previous_version='',
    previous_version_name='',
    has_changes=True
)
```

### Merge from `release` to `release-beta` (Second fix version)

Latest tag on `release`: `0.0.2-pre`

```python
ActionArguments(
    prefix='v',
    suffix='beta',
    previous_version_suffix='pre',
    bumping_suffix='hotfix',
    only_bump_suffix=True,
    create_tag=True
)

ActionOutputs(
    version='0.0.2-beta',
    version_name='v0.0.2-beta',
    previous_version='0.0.1-beta',
    previous_version_name='v0.0.1-beta',
    has_changes=True
)
```

### Cherrypick from `main` to `release-beta`

Latest tag on `release`: `0.0.2-pre`
Latest tag on `release-beta`: `0.0.2-beta`

```python
ActionArguments(
    prefix='v',
    suffix='beta',
    previous_version_suffix='pre',
    bumping_suffix='hotfix',
    only_bump_suffix=True,
    create_tag=True
)

ActionOutputs(
    version='0.0.2-beta-hotfix.1',
    version_name='v0.0.2-beta-hotfix.1',
    previous_version='0.0.2-beta',
    previous_version_name='v0.0.2-beta',
    has_changes=True
)
```
